services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fulldemo_flask
    depends_on:
      - mysql  
      # - mongo  # Ensure MongoDB starts before the web service
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: fulldemo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company_b
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 4000:4001

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fulldemo_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8070:80

  # mongo:
  #   image: mongo:latest
  #   container_name: fulldemo_mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo_data:/data/db


volumes:
  mysql_data:
  # mongo_data:




